language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dakshbhardwaj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dakshbhardwaj/react-test npm test -- --coverage

after_success:
  - docker build -t dakshbhardwaj/multi-client ./client
  - docker build -t dakshbhardwaj/multi-nginx ./nginx
  - docker build -t dakshbhardwaj/multi-server ./server
  - docker build -t dakshbhardwaj/multi-worker ./worker
  #Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it to the docker hub
  - docker push dakshbhardwaj/multi-client
  - docker push dakshbhardwaj/multi-nginx
  - docker push dakshbhardwaj/multi-server
  - docker push dakshbhardwaj/multi-worker
  # deploy
  # provider
  # region
  # app
  # env
  # bucket_name
  #bucket_path: docker_multi
  #on
  #branh:master
  #access_key_id
  #acess_secret_key
